plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

ext {
    junitVersion = "5.10.0"
}

def dataDir = "${rootProject.projectDir}/data"

allprojects {
    group = 'dev.atomixsoft.solar_eclipse'
    version = '0.3.1.1-alpha'

    repositories {
        mavenCentral()
        maven {
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
}

subprojects {
    apply plugin: 'java'

    dependencies {
        testImplementation platform('org.junit:junit-bom:' + junitVersion)
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    plugins.withId('application') {
        tasks.named('run', JavaExec).configure {
            doFirst {
                classpath = files(dataDir) + classpath
                workingDir = file(dataDir)
            }
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).tap {
        configureEach {
            useJUnitPlatform()
        }
    }
}
