plugins {
    id 'application'
}

ext {
    nettyVersion = "4.2.0.Final"
}

def dataDir = "${rootProject.projectDir}/data"

application {
    mainClass = 'dev.atomixsoft.solar_eclipse.server.Server'
}

dependencies {
    implementation project(':core')
    implementation 'io.netty:netty-all:' + nettyVersion
}

tasks.register('debug', JavaExec).configure {
    doFirst {
        classpath = files(dataDir) + sourceSets.main.runtimeClasspath
        workingDir = file(dataDir)

        println "Classpath is set to ${classpath.asPath}"
        println "Working directory is $workingDir"
    }

    group = 'application'
    description = 'Runs the Solar Eclipse Server in debug mode'

    standardInput = System.in

    mainClass = application.mainClass.get()
    
    jvmArgs = [
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
    ]
    ignoreExitValue = true

    doLast {
        logging.level = LogLevel.INFO
        println "Debugging Solar Eclipse Server..."
    }
}

tasks.named('run', JavaExec) {
    group = 'application'
    description = 'Runs the Solar Eclipse Server'
}
